import Head from "next/head";
import { Heading } from "@chakra-ui/react";
import PageContentLayout from "@/components/Layout/PageContentLayout";

export default function Home() {
  return (
    <>
      <Head>
        <title>Boilerplate NextChakra</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <PageContentLayout>
        <Heading textAlign="center">Home</Heading>
      </PageContentLayout>
    </>
  );
}

export { getServerSideProps } from "@/chakra/chakra";
