import { Box, Text, VStack } from '@chakra-ui/react';
import Head from 'next/head';

import { buttonVisuals } from '@/chakra/components/button.recipe';
import {
  headingRole,
  headingSize,
  headingSpacing,
  headingTransform,
  headingWeight,
} from '@/chakra/components/heading.recipe';
import { Button, VariantGrid } from '@/components';
import { Heading } from '@/components/ui/Heading';

export default function Home() {
  return (
    <>
      <Head>
        <title>Boilerplate NextChakra</title>
        <meta content="Generated by create next app" name="description" />
        <meta content="width=device-width, initial-scale=1" name="viewport" />
        <link href="/favicon.ico" rel="icon" />
      </Head>

      <VStack
        bgImage="radial-gradient(rgba(255,255,255,0.15) 1px, transparent 0)"
        bgPos="0 0"
        bgSize="28px 28px"
      >
        <VStack
          alignItems={'flex-start'}
          justifyContent={'center'}
          minHeight={{ base: '92vh', md: '100vh' }}
          width={{ base: '90%', sm: '90%', md: '75%', lg: '66%' }}
        >
          <Heading weight="thin">Welcome to the Emperor's</Heading>
          <Heading mb={12} weight="bold">
            Component Library
          </Heading>
          <Text fontSize="  lg">
            A showcase of all available components and their variants.
          </Text>
        </VStack>

        <VStack
          gap={{ base: 32, sm: 50, md: 64 }}
          px={{ base: 4, sm: 8 }}
          width="100%"
        >
          {/* Button Component Showcase */}
          <Box width="100%">
            <Heading mb={8} role={'sectionTitle'}>
              Buttons
            </Heading>
            <VariantGrid
              render={(variant) => <Button visual={variant}>{variant}</Button>}
              title="Visual Variants"
              variants={buttonVisuals}
            />
          </Box>

          {/* Heading Component Showcase */}
          <Box width="100%">
            <Heading mb={8} role={'sectionTitle'}>
              Headings
            </Heading>
            <VStack gap={16} width="100%">
              <VariantGrid
                render={(variant) => (
                  <Heading role={variant}>{variant}</Heading>
                )}
                title="Role Variants"
                variants={headingRole}
              />
              <VariantGrid
                render={(variant) => (
                  <Heading weight={variant}>{variant}</Heading>
                )}
                title="Weight Variants"
                variants={headingWeight}
              />
              <VariantGrid
                render={(variant) => (
                  <Heading size={variant}>{variant}</Heading>
                )}
                title="Size Variants"
                variants={headingSize}
              />
              <VariantGrid
                render={(variant) => (
                  <Heading spacing={variant}>{variant}</Heading>
                )}
                title="Spacing Variants"
                variants={headingSpacing}
              />
              <VariantGrid
                render={(variant) => (
                  <Heading transform={variant}>{variant}</Heading>
                )}
                title="Transform Variants"
                variants={headingTransform}
              />
            </VStack>
          </Box>
        </VStack>
      </VStack>
    </>
  );
}
