import { Flex, Heading } from '@chakra-ui/react';
import Head from 'next/head';

export default function Home() {
  return (
    <>
      <Head>
        <title>Boilerplate NextChakra</title>
        <meta content="Generated by create next app" name="description" />
        <meta content="width=device-width, initial-scale=1" name="viewport" />
        <link href="/favicon.ico" rel="icon" />
      </Head>

      <Flex align="center" direction="column" justify="center" mt="100px">
        <Heading textAlign="center">Home</Heading>
      </Flex>
    </>
  );
}
